{
 "title": "42SegBot",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Level",
   "type": "bargauge",
   "gridPos": { "h": 22, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  login,\n  level\nFROM users\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Overall",
   "type": "table-old",
   "gridPos": { "h": 17, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT login, location, level, correction_point FROM users"
    }
   ]
  },
  {
   "title": "Levels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  login,\n  level\nFROM users"
    }
   ]
  }
 ]
}